colleges/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import view_course, request_course

app_name = 'colleges'

urlpatterns = [
    path('courses/<int:course_id>/<slug:course_slug>/', view_course, name='course'),
    path('courses/add/', TemplateView.as_view(template_name='courses/RequestAddCourse.html'), name='request_course'),
]
#     path('', views.get_colleges, name='all_colleges'),
#     path('<int:college_id>/<slug:college_slug>/', include([
#         path('', views.college_home, name='college_home'),
#         path('dorms/', views.college_on_campus_living, name='dorms'),
#
#         # moderation links
#         path('edit/', views.edit_college),
#         path('edit/residential-areas/', views.get_moderated_resAreas),
#         path('edit/dorms', views.get_moderated_dorms),
#
#         # professors
#         # path('professors/', professor_view.get_all_college_professors, name='professors'),
#         path('professors/', search_view.ProfessorSearchView.as_view(), name='professors'),
#         path('professors/<int:professor_id>/', professor_view.get_college_professor, name='professor'),
#         path('professors/<int:professor_id>/<slug:professor_slug>/', professor_view.get_college_professor,
#              name='professor'),
#
#         # courses
#         path('courses/', search_view.CoursesSearchView.as_view(), name='courses'),
#         path('courses/<int:course_id>/', courses_view.college_course, name='course'),
#         path('courses/<int:course_id>/<slug:course_slug>/', courses_view.college_course, name='course'),
#
#         # search
#         path('professors/search/', search_view.ProfessorSearchView.as_view(), name='professor_search'),
#         path('professors/search/results/', search_view.ProfessorSearchView.as_view(), name='search_results'),
#
#         path('courses/search/', search_view.CoursesSearchView.as_view(), name='course_search'),
#         path('courses/search/results/', search_view.CoursesSearchView.as_view(), name='search_results'),
#
#         # request add object
#         path('courses/add/', views.request_add_course, name='request_add_course'),
#         path('professors/add/', views.request_add_professor, name='request_add_professor'),
#
#     ])),
# ]

notetakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from colleges.views import home, FilterCourseView

urlpatterns = [
    path('', FilterCourseView.as_view(), name='home'),
    path('apply/', TemplateView.as_view(template_name='Apply.html'), name='apply'),
    path('admin/', admin.site.urls),
    path('contact/', TemplateView.as_view(template_name='Contact.html'), name='contact'),
    path('colleges/', include('colleges.urls'), name='colleges'),
]

templates/AlertMessages.html
{% if messages %}
    <ul>
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
                     role="alert">
                        <span class="font-medium">
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        </span>
                </div>
            {% else %}
                <div class="p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400"
                     role="alert">
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                </div>

            {% endif %}
        {% endfor %}
    </ul>
{% endif %}

templates/Apply.html
{% extends 'Base.html' %}
{% load static %}

{% block content %}


        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSe-ZqYczc2LHNqJ5BcQKXEeM47GJfCYNUyYSWQveXF0cjQQLA/viewform?embedded=true" class="w-full h-full" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>



{% endblock %}

templates/Base.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Notetakers</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% compress css %}
        <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}
    {% block head %} {% endblock %}
</head>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-P6JY8X8892"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-P6JY8X8892');
</script>

<body>
    <nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
      <div class="container flex flex-wrap items-center justify-between mx-auto">
        <a href="{% url 'home'  %}" class="flex items-center">
            <img src="{% static 'images/logo.png' %}" class="h-6 mr-3 sm:h-9" alt="Notetaker Logo" />
            <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Notetakers</span>
        </a>
        <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-default">
          <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <li>
              <a href="{% url 'home' %}" class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Home</a>
            </li>
            <li>
              <a href="{% url 'apply' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Apply</a>
            </li>
            <li>
              <a href="{% url 'colleges:request_course' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Add Course</a>
            </li>
            <li>
              <a href="{% url 'contact' %}"  class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

     <div class="container mx-auto mt-4 w-full h-screen">
        {% block content %}
        {% endblock %}

        <footer class="p-4 md:px-6 md:py-8 dark:bg-gray-900">
            <div class="sm:flex sm:items-center sm:justify-between">
                <a href="{% url 'home' %}" class="flex items-center mb-4 sm:mb-0">
                    <img src="{% static 'images/logo.png' %}" class="h-8 mr-3" alt="Logo" />
                    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Notetakers</span>
                </a>
                <ul class="flex flex-wrap items-center mb-6 text-sm text-gray-500 sm:mb-0 dark:text-gray-400">
                    <li>
                        <a href="{% url 'contact' %}"  class="mr-4 hover:underline md:mr-6 ">Contact</a>
                    </li>
                </ul>
            </div>
        </footer>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
</body>

templates/Contact.html
{% extends 'Base.html' %}
{% load static %}

{% block content %}
{##}
{#  <section class="bg-white dark:bg-gray-900">#}
{#  <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">#}
{#      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Contact Us</h2>#}
{#      <p class="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">Got a technical issue? Want to send feedback about our product? Let us know. </p>#}
       <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSclXgWIaqFzYVDekljGC5oqEkP8mgloqDm_6K8uMwNLFaFo-g/viewform?embedded=true" class="w-full h-full" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
{#      <form action="#" class="space-y-8">#}
{#          <div>#}
{#              <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your email</label>#}
{#              <input type="email" id="email" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="name@gmail.com" required>#}
{#          </div>#}
{#          <div>#}
{#              <label for="subject" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Subject</label>#}
{#              <input type="text" id="subject" class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="Let us know how we can help you" required>#}
{#          </div>#}
{#          <div class="sm:col-span-2">#}
{#              <label for="message" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Your message</label>#}
{#              <textarea id="message" rows="6" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Leave a comment..."></textarea>#}
{#          </div>#}
{#          <button type="submit" class="py-3 px-5 text-sm font-medium text-center text-white rounded-lg bg-primary-700 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Send message</button>#}
{#      </form>#}
{#  </div>#}
{#</section>#}
{% endblock %}

templates/MVP.html
{% extends 'Base.html' %}
{% load static %}
{% load render_table from django_tables2 %}
{% load tailwind_filters %}



{% block content %}
    <section class="bg-white dark:bg-gray-900 overflow-auto m-2">
        <div class="p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
            <svg aria-hidden="true" class="flex-shrink-0 inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
            <span class="font-medium">Click on your class to find a notetaker.</span>
        </div>
        {% include 'AlertMessages.html' %}



            <h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">UMass Amherst Notetakers</h1>
            <div class="relative overflow-x-auto">
                {% if filter %}
                   <form method="get">
                        <div class="grid md:grid-cols-4 md:gap-6">
                          <div class="relative z-0 w-full mb-6 group">
                            {{ filter.form.course_id|as_crispy_field }}
                          </div>
                          <div class="relative z-0 w-full mb-6 group">
                            {{ filter.form.course_name|as_crispy_field }}
                          </div>
                        <div class="relative z-0 w-full mb-6 group">
                            {{ filter.form.department|as_crispy_field }}
                          </div>
                        </div>
                        <input type="submit"  class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 relative z-0 w-full mb-6 group" />
                   </form>
                {% endif %}
                {% render_table table %}
            </div>
    </section>
{% endblock %}

templates/Table.html
{% load django_tables2 %}
{% load i18n %}
{% load static %}


    <table class="w-full table-auto text-sm text-left text-gray-500 dark:text-gray-400">
        {% block table.thead %}
        {% if table.show_header %}
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                {% for column in table.columns %}
                    <th scope="col" class="px-6 py-3">
                        {% if column.orderable %}
                            <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                        {% else %}
                            {{ column.header }}
                        {% endif %}
                    </th>
                {% endfor %}
                </tr>
            </thead>
        {% endif %}
        {% endblock table.thead %}
        {% block table.tbody %}
            <tbody>
            {% for row in table.paginated_rows %}
                {% block table.tbody.row %}
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    {% for column, cell in row.items %}
                        <td class="px-6 py-4"{{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                    {% endfor %}
                </tr>
                {% endblock table.tbody.row %}
            {% empty %}
                {% if table.empty_text %}
                {% block table.tbody.empty_text %}
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700"><td class="px-6 py-4" colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                {% endblock table.tbody.empty_text %}
                {% endif %}
            {% endfor %}
            </tbody>
        {% endblock table.tbody %}
        {% block table.tfoot %}
        {% if table.has_footer %}
        <tfoot {{ table.attrs.tfoot.as_html }}>
            <tr>
            {% for column in table.columns %}
                <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
            {% endfor %}
            </tr>
        </tfoot>
        {% endif %}
        {% endblock table.tfoot %}
    </table>


{% block pagination %}
    {% if table.page and table.paginator.num_pages > 1 %}
    <ul class="inline-flex items-center -space-x-px shrink">
        {% if table.page.has_previous %}
            {% block pagination.previous %}
                <li>
                  <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    <span class="sr-only">Previous</span>
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                  </a>
                </li>
            {% endblock pagination.previous %}
        {% endif %}
        {% if table.page.has_previous or table.page.has_next %}
        {% block pagination.range %}
            {% for p in table.page|table_page_range:table.paginator %}
                <li class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" {% if p == table.page.number %} aria-current="page" {% endif %}>
                    {% if p == '...' %}
                        <a href="#">
                            {{ p }}
                        </a>
                    {% else %}
                        <a href="{% querystring table.prefixed_page_field=p %}">
                            {{ p }}
                        </a>
                    {% endif %}
                </li>
            {% endfor %}
        {% endblock pagination.range %}
        {% endif %}
        {% if table.page.has_next %}
            {% block pagination.next %}
                <li>
                    <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                        <span class="sr-only">Next</span>
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                    </a>
                </li>
            {% endblock pagination.next %}
        {% endif %}
    </ul>
    {% endif %}
{% endblock pagination %}